# Generated by Django 2.1.2 on 2018-11-12 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20181112_2243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='title',
            new_name='Value',
        ),
        migrations.RemoveField(
            model_name='note',
            name='body',
        ),
    ]
